### ISSUE TITLE
access violation...need help

### ISSUE THREAD

**Issue by enchantedwolfe** [coreybutler/fenix#73] opened 2016-12-03 22:30 UTC
I'm running windows 10 and trying to install Fenix but everytime I try this error comes up

Access violation at address 23218B86 im module 'wsftpsi.dll'. Read of address 00000000.

Any help would be appreciated.

**Comment by coreybutler** [comment] 2016-12-05 20:13
Are you trying to install Fenix 2 or the beta of Fenix 3? Have you tried running the installer as admin?

**Comment by enchantedwolfe** [comment] 2016-12-07 21:12
I'm running Fenix 3, but I figured out that the wsftpsi.dll was part of my ftp program so I uninstalled it and reinstalled Fenix and now it works fine.  I just hope when I re-install my ftp program that it doesn't cause a clash with Fexnix.  By the way my ftp program is WS_FTP Pro.

**Comment by coreybutler** [comment] 2016-12-07 21:34
That's very strange... I haven't come across this issue before. Fenix doesn't utilize that dll file, so the only thing I can think of is perhaps the WS FTP is locking the file system and preventing other utilities from accessing it. Thanks for posting. Since the issue is resolved for you and appears unrelated, I'll close it. If you or anyone else sees something similar, feel free to re-open the issue.

**Closed by coreybutler** 2016-12-07 21:34 UTC
